---
title: "BIO1007A"
author: "Andrew Planting"
date: "2023-01-15"
output:
   prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Weekly Assignment 1

#### Getting Started

* Download Rstudio 

* Download git specific to your computer 
  + Mac users will need to install homebrew using this code in the terminal (not console)
    + /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 
    + brew install git
  + Ensure that Xcode is installed (ensure that the git version is compatible with your computer's operating        system)
    + The full Xcode app is not needed, just the essentials. Rstudio will prompt you to download the essentials       when installing homebrew 
        + Do NOT attempt to do this while multiple people in the same room are trying to do the same (it will             take hours... )
        + Instead, leave the room and find a different server to connect to. This should speed up the process

#### Setting up a GitHub Repo
* Create a GitHub account 
* Create personal access token (PAT)
  + Follow these steps in order
    + Developer settings --> personal access tokens --> generate new "classic" token --> name as desired and          choose desired expiration date --> check the "repo" box --> generate token and be sure to save the              generated number
  
    + Install the credentials package by typing the following code
      + install.packages("credentials")
      + git config --global user.email "put github email here"
        git config --global user.name "put your name here"
        credentials::set_github_pat("put PAT here")
        
* Now you are ready to create your repo
  + Create a new repo by clicking "+" --> name as desired
    + Include a READme file and select a license (MIT works just fine)
    + Do NOT include a gitignore
    
#### Creating and linking the R project to your GitHub repo
* In Rstudio 
  + Click on "new project" in the upper rightmost corner of your screen 
  + Click "version control" and select "git"
* On GitHub
  + Click the green "Code" button and copy the URL 
* In Rstudio
  + Paste the copied URL into the designated URL box
  + Name the repo EXACTLY the same thing you named it on GitHub
  + Save this project to a desired location on your local computer 
  + Click "Create Project"

#### Creating a webpage portal to be hosted by GitHub and hosting the index page
* In Rstudio
  + Create a new R markdown file 
  + Title something along the lines of "setting up home webpage"
  + Save the file with the name "index" --> knit to .html 
* On GitHub
  + Go to your repo's settings 
    + Under "pages" on the lefthand side click "source"
    + Change from none to "main branch"

#### Committing changes 
* We need to commit all these changes to GitHub!
* In terminal
  + Check git status to make sure there are changes to commit using "git status"
  + Add any changes using "git add -A"
  + Commit changes using "git commit -am 'desired commit message'"
  + Push changes to GitHub using "git commit"
  + Check git status again to make sure everything is up to date 
* You do not need to do this after each change. Do it enough to save your work, but it doesn't need to get        annoying to do!

#### Troubleshooting
* Ensure you haven't misspelled anything in your code or missed a parenthesis/bracket
* When installing homebrew, ensure you have sufficient bandwidth to install the essential Xcode files 
    + Adequate bandwidth will prevent this step from taking hours
    + You do NOT need the 10 GB app!
* Make sure everything is labeled corectly. Your Rstudio project must be labeled exactlty the same as the GitHub repo you are saving it to
* Ensure you have added, committed, and pushed your changes using TERMINAL not console
* Be patient! Sometimes it takes a few minutes for pushes to updated on GitHub